shop/urls.py
from django.urls import path
from shop import views
from .views import index, cat_obj, item_detalles, guardar_item, add_to_cart, ver_carrito, ver_favoritos, quitar_del_carrito, buscador, buscador_ajax, comentarios, categorias, vaciar_carro
from django.contrib.auth.decorators import login_required
app_name = 'shop'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:id>/items/', views.cat_obj, name='cat_obj'),
    path('categorias/', views.categorias, name='categorias'),
    path('<int:id>/items/detalles/', views.item_detalles, name='item_detalles'),
    path('<int:id>/guardar/', views.guardar_item, name='guardar'),
    path('<int:id>/agregar/', views.add_to_cart, name='add'),
    path('carrito/', login_required(views.ver_carrito), name='carrito'),
    path('favoritos/', login_required(views.ver_favoritos), name='favs'),
    path('<int:id>/quitar/', login_required(views.quitar_del_carrito), name='quitar'),
    path('buscar/', views.buscador, name='buscar'),
    path('resultadosajax/', views.buscador_ajax, name='buscar_ajax'),
    path('<int:id>/comentar/', login_required(views.comentarios), name='comentarios'),
    path('vaciar/', views.vaciar_carro, name='vaciar'),
]

shopIT/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import logout_then_login

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls')),
    path('usuario/', include('usuario.urls')),
    path('logout/', logout_then_login, name='logout')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/models.py
from django.db import models
from django.contrib.auth.models import User
from decimal import Decimal
from django.db.models import F, Sum

Metodos = (
    ('td', 'Tarjeta de Debito'),
    ('ef', 'Efectivo'),
    ('tc', 'Tarjeta de Credito')
)
class Categoria(models.Model):
    nombre = models.CharField(max_length=200)

    def __str__(self):
        return(self.nombre)

class Item(models.Model):
    nombre = models.CharField(max_length=100)
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE)
    imagen = models.ImageField(blank=True, null=True, upload_to='covers/%Y/%m/%D/')
    precio = models.FloatField()
    descripcion = models.TextField()
    añadir_a_favs = models.ManyToManyField(User, related_name='fav_items', blank=True)

    def __str__(self):
        return self.nombre

class OrderItem(models.Model):
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    cantidad = models.IntegerField(default=1)

    def __str__(self):
        return f"{self.cantidad} of {self.item.nombre}"

    def total_item(self):
        return self.cantidad * self.item.precio

class Direccion(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    provincia = models.CharField(max_length=100)
    localidad = models.CharField(max_length=100)
    codigo_postal = models.IntegerField()
    direccion = models.CharField(max_length=70)

class Order(models.Model):
    items_ordered = models.ManyToManyField(OrderItem)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    fecha = models.DateField(auto_now_add=True)
    direccion_envio = models.ForeignKey(Direccion, on_delete=models.CASCADE, null=True)

    def get_items(self):
        return(self.items_ordered.all())

    def get_total(self):
        total = 0
        for order_item in self.items_ordered.all():
            total += order_item.total_item()
        return total

class Review(models.Model):
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    texto = models.TextField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    fecha = models.DateField(auto_now_add=True)
    calificacion = models.IntegerField(default=1)

    def __str__(self):
        return self.texto

shop/views.py
from django.utils import timezone
from django.shortcuts import render, get_object_or_404
from django.http import Http404, JsonResponse, HttpResponse
from django.contrib.auth.models import User
from .models import Item, OrderItem, Order, Review, Categoria
from django.db.models import Q
from django.db.models import Avg
import math
from django.views.decorators.csrf import csrf_protect

def index(request):
    cat = Categoria.objects.all()[:5]
    nuevos_ingresos = Item.objects.order_by("-id")[:4]
    return render(request, 'shop/index.html', {'cat': cat, 'nuevos': nuevos_ingresos})

def cat_obj(request, id):
    try:
        catobj = Categoria.objects.get(pk=id)
    except Categoria.DoesNotExist():
        raise Http404("La categoria no existe")
    return render(request, 'shop/cat_obj.html', {'catobj':catobj})

def categorias(request):
    try:
        cat = Categoria.objects.all()
    except Categoria.DoesNotExist():
        raise Http404("La categoria no existe")
    return render(request, 'shop/cats.html', {'cat':cat})

def item_detalles(request, id):
    is_favourite = False
    is_in_cart = False
    try:
        get_item = Item.objects.get(pk=id)
        get_comentarios = Review.objects.filter(item=get_item)
        avg_cal = get_comentarios.aggregate(average_rating=(Avg('calificacion')))
        if get_item.añadir_a_favs.filter(id=request.user.id).exists():
            is_favourite = True
        if OrderItem.objects.filter(user=request.user.id, item=get_item).exists():
            is_in_cart = True
    except Item.DoesNotExist:
        raise Http404('el item no existe')
    context = {
        'get_item':get_item,
        'is_favourite': is_favourite,
        'is_in_cart': is_in_cart,
        'comentarios': get_comentarios,
        'avg_cal': avg_cal
    }
    return render(request, 'shop/item.html', context)

def guardar_item(request, id):
    salida = {}
    item = get_object_or_404(Item, id=id)
    if item.añadir_a_favs.filter(id=request.user.id).exists():
        salida = {'quitar': True, 'msj': 'quitado'}
        item.añadir_a_favs.remove(request.user)
    else:
        item.añadir_a_favs.add(request.user)
        salida = {'agregar': True, 'msj': 'agregado'}
    return HttpResponse(JsonResponse(salida))

def ver_favoritos(request):
    favs = Item.objects.filter(añadir_a_favs=request.user.id)
    context = {'favs': favs}
    return render(request, 'shop/favoritos.html', context)

@csrf_protect
def add_to_cart(request,id):
    salida = {}
    if request.method == 'POST' and request.is_ajax():
        cantidad_ = request.POST.get('cantidad')
        try:
            item = get_object_or_404(Item, id=id)
            order_item = OrderItem.objects.create(item=item, user=request.user, cantidad=cantidad_)
            full_order = Order.objects.filter(user=request.user)
            if full_order.exists():
                order_qs = full_order[0]
                order_qs.items_ordered.add(order_item)
                salida = {'success': True, 'msj': 'Añadido al carrito'}
            else:
                ordered_date = timezone.now()
                order = Order.objects.create(user=request.user, fecha=ordered_date)
                order_item.save()
                order.items_ordered.add(order_item)
                salida = {'success': True, 'msj': 'Añadido al carrito'}
        except Item.DoesNotExist:
            salida = {'error': True, 'msj': 'El item no es recibido correctamente'}
    return HttpResponse(JsonResponse(salida))

@csrf_protect
def quitar_del_carrito(request, id):
    exit_ = {}
    try:
        item = get_object_or_404(Item, id=id)
        order = Order.objects.filter(user=request.user)
        if order.exists():
            order_qs = order[0]
            order_item = OrderItem.objects.filter(user=request.user.id, item=item)[0]
            order_qs.items_ordered.remove(order_item)
            order_item.delete()
            exit_ = {'exito': True, 'msj': 'Item quitado'}
        else:
            exit_ = {'error': True, 'msj': 'La orden no existe'}
    except Item.DoesNotExist:
        exit_ = {'error': True, 'msj': 'El item no es recibido correctamente'}
    return HttpResponse(JsonResponse(exit_))

@csrf_protect
def vaciar_carro(request):
    exit_ = {}
    try:
        order = Order.objects.filter(user=request.user)
        items_in_cart = OrderItem.objects.filter(user=request.user.id)
        items_in_cart.delete()
        order.delete()
        exit_ = {'success': True, 'msj': 'Carro Vacio'}
    except Order.DoesNotExist:
        exit_ = {'error': True, 'msj': 'La orden no es recibida correctamente'}
    return HttpResponse(JsonResponse(exit_))

def ver_carrito(request):
    carrito = Order.objects.filter(user=request.user)
    context = {'carrito': carrito}
    return render(request, 'shop/carrito.html', context)

def buscador(request):
    try:
        nombre_ = request.GET.get('q')
        obj = Item.objects.filter(nombre__icontains=nombre_)
    except Item.DoesNotExist:
        raise Http404('objetos no encontrados')
    return render(request, 'shop/resultados.html', {'objetos': obj})


def buscador_ajax(request):
    salida = {}
    item = request.GET.get('q')
    if request.is_ajax():
        objeto = Item.objects.filter(Q(nombre__icontains=item))
        resultados = []
        for obj in objeto:
            basic = {}
            basic['id'] = obj.id
            basic['nombre'] = obj.nombre
            resultados.append(basic)
        salida = {'exito': True, 'objetos': resultados}
    else:
        objeto = []
        salida = {'vacio': True, 'objetos': objeto}
    return HttpResponse(JsonResponse(salida))

@csrf_protect
def comentarios(request, id):
    salida = {}
    if request.method == 'POST' and request.is_ajax():
        texto_ = request.POST.get('texto')
        calificacion_ = request.POST.get('rating_value')
        try:
            item = get_object_or_404(Item, id=id)
            date = timezone.now()
            if texto_ and calificacion_:
                comentario = Review.objects.create(item=item, user=request.user, texto=texto_, fecha=date, calificacion=calificacion_)
                comentario.save()
                resultados = []
                basic = {}
                name_ = request.user.username
                basic['comentario'] = comentario.texto
                basic['user'] = name_
                basic['fecha'] = comentario.fecha
                basic['calificacion'] = comentario.calificacion
                resultados.append(basic)
                salida = {'exito': True, 'objetos': resultados}
            else:
                salida = {'error': True, 'msj': 'ups, parace que te has olvidado de dejar una calificacion'}
        except Item.DoesNotExist:
            salida = {'error': True, 'msj': 'El item no es recibido correctamente'}
    return HttpResponse(JsonResponse(salida))

templates/shop/carrito.html
{% extends 'base.html' %}
{% block header %}
<div class="header">
    <div class="titulo_principal">
        <a href="{% url 'shop:index' %}">ShopIT</a>
    </div>
</div>
{% endblock %}
{% block content %}
<div class="container">
    <h1 class="sub">Carrito</h1>
    <table class="table m-2">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Producto</th>
                <th scope="col">Precio x unidad</th>
                <th scope="col">Cantidad</th>
              </tr>
        </thead>
        <tbody id="vacio">
            {% for cart in carrito %}
            {% for items in cart.items_ordered.all %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{ items.item.nombre }}</td>
                <td>{{ items.item.precio }}</td>
                <td>{{ items.cantidad }}</td>
            </tr>
            {% endfor %}
            <tr>
                <td>Total:</td>
                <td></td>
                <td></td>
                <td>{{ cart.get_total }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {% if carrito|length > 0 %}
    <div class="vaciar_carro p-2">
        <form>
            {% csrf_token %}
            <button id="vaciar" value="{{ carrito.id }}" type="submit"><i class="fas fa-trash-alt"></i></button>
        </form>
    </div>
    {% else %}
    <div class="carro_vacio p-2">
        <h1 class="sub" style="color: #6d6d6d;">Carro vacio por el momento</h1>
    </div>
    {% endif %}
</div>
{% endblock %}

templates/shop/cat_obj.html
{% extends 'base.html' %}
{% block content %}
<div class="cat">
    <h1 class="sub" id="sub_01">{{ catobj.nombre }}</h1>
    <div class="cat_">
        {% if not forloop.last %}
        {% for item in catobj.item_set.all %}
            <div class="cat_obj">
                <a href="{% url 'shop:item_detalles' id=item.id %}">
                    <img class="img_in_cat" src={% if item.imagen %}'{{item.imagen.url}}'{% endif %}>
                    <p class="p_item_cat2">{{ item.nombre }}</p>
                    <p class="p_item_cat">{{ item.precio }}</p>
                </a>
            </div>
        {% endfor %}
        {% endif %}
    </div>
    <div class="cat_res">
        <h1 class="sub">{{ catobj.nombre }}</h1>
        {% for item in catobj.item_set.all %}
        <div class="cat_obj3">
            <a href="{% url 'shop:item_detalles' id=item.id %}">
                <img class="img_in_cat" src={% if item.imagen %}'{{item.imagen.url}}'{% endif %}>
                <p class="p_item_cat2">{{ item.nombre }}</p>
                <p class="p_item_cat">{{ item.precio }}</p>
            </a>
        </div>
    {% endfor %} 
    </div>
</div>
{% if not catobj.item_set.all %}
        <h4 class="sub text-center">Lo sentimos, no hay productos por el momento</h4>
    {% endif %}
{% endblock %}

<p>{{ item.nombre }}</p>
<p>{{ item.precio }}</p>

templates/shop/cats.html
{% extends 'base.html' %}
{% block content %}
<div style="padding-top: 120px;">
    <h1 class="sub">Categorias</h1>
</div>
<div class="p-4">
    <nav class="category">
        <ul>
            {% for cats in cat %}
                <li><a href="{% url 'shop:cat_obj' id=cats.id %}">{{ cats.nombre }}</a></li>
            {% endfor %}
        </ul>
    </nav>
</div>
{% endblock %}

templates/shop/favoritos.html
{% extends 'base.html' %}
{% block header %}
<div class="header">
    <div class="titulo_principal">
        <a href="{% url 'shop:index' %}">ShopIT</a>
    </div>
</div>
{% endblock %}
{% block content %}
<div class="fav_tit" style="padding-top: 120px;">
    <h1 class="sub">Items guardados</h1>
</div>
<div class="cat_">
    {% if not forloop.last %}
    {% for favorito in favs %}
    <div class="cat_obj">
        <a href="{% url 'shop:item_detalles' id=favorito.id %}">
            <img class="img_in_cat" src={% if favorito.imagen %}'{{favorito.imagen.url}}'{% endif %}>
            <p class="p_item_cat2">{{ favorito.nombre }}</p>
            <p class="p_item_cat">$ {{ favorito.precio }}</p>
        </a>
    </div>
    {% endfor %}
    {% endif %}
</div>
<div class="cat_res">
    <h1 class="sub" style="padding-top: 80px">Favoritos</h1>
    {% for favorito in favs %}
    <div class="cat_obj3">
        <a href="{% url 'shop:item_detalles' id=favorito.id %}">
            <img class="img_in_cat" src={% if favorito.imagen %}'{{favorito.imagen.url}}'{% endif %}>
            <p class="p_item_cat2">{{ favorito.nombre }}</p>
            <p class="p_item_cat">$ {{ favorito.precio }}</p>
        </a>
    </div>
{% endfor %} 
</div>
{% endblock %}

templates/shop/index.html
{% extends 'base.html' %}
{% block content %}
<div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img id="img1" class="d-block w-100" src="/media/img/212.png" style="height: 350px;" alt="First slide">
      <div class="carousel-caption d-md-block">
        <i class="fas fa-mobile-alt" id="icon_carousel"></i>
        <h2 class="carousel_title1">Encontra lo mejor en tecnologia</h2>
        <a href="{% url 'shop:cat_obj' id=2 %}" class="ver_ahora">Ver ahora</a>
      </div>
    </div>
    <div class="carousel-item">
      <img id="img2" class="d-block w-100" src="/media/img/angryim.png" style="height: 350px;" alt="Second slide">
      <div class="carousel-caption d-md-block">
        <i class="fas fa-mobile-alt" id="icon_carousel3"></i>
        <h2 class="carousel_title2">Motorola Moto G8</h2>
        <a href="{% url 'shop:item_detalles' id=3 %}" class="ver_ahora2">Ver ahora</a>
      </div>
    </div>
    <div class="carousel-item">
      <img id="img3" class="d-block w-100" src="/media/img/angryimg (4).png" style="height: 350px;" alt="Third slide">
      <div class="carousel-caption d-md-block">
        <i class="fas fa-tshirt" id="icon_carousel2"></i>
        <h2 class="carousel_title1">Encontra esa ropa que tanto buscabas</h2>
        <a href="{% url 'shop:cat_obj' id=4 %}" class="ver_ahora">Ver ahora</a>
      </div>
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
<div class="categorias">
  <h4 class="sub">Categorias</h4>
  <a class="mas" href="{% url 'shop:categorias' %}" data-toggle="tooltip" title="Ver Mas"><i class="fas fa-chevron-right"></i></a>
  {% for categoria in cat %}
  <svg height="200" width="200">
    <a href="{% url 'shop:cat_obj' id=categoria.id %} " class="circ_a">
      <circle class="circs" cx="100" cy="100" r="80" fill="#CFC4C7"/>
      <text x="50%" y="50%" class="text_1" text-anchor="middle" style="font-family: 'Raleway', sans-serif;">{{ categoria.nombre }}{% if not forloop.last %}{% endif %}</text>
    </a>
  </svg>
  {% endfor %}
  <div class="cat_responsive">
      {% for categoria in cat %}
      <svg height="120" width="120">
        <a href="{% url 'shop:cat_obj' id=categoria.id %}" class="circ_a">
          <circle class="circs" cx="60" cy="60" r="50" fill="#CFC4C7"/>
          <text x="50%" y="50%" class="text_1" text-anchor="middle" style="font-family: 'Raleway', sans-serif;">{{ categoria.nombre }}{% if not forloop.last %}{% endif %}</text>
        </a>
      </svg>
      {% endfor %}
  </div>
  <div class="carousel_cat">
    <div id="carouselcat" class="carousel slide" data-ride="carousel">
      <div class="carousel-inner" role="listbox">
        {% for categoria in cat %}
          {% if forloop.counter == 1 %}
            <div class="carousel-item active">
          {% else %}
            <div class="carousel-item">
          {% endif %}
            <svg height="200" width="200">
              <a href="{% url 'shop:cat_obj' id=categoria.id %}" class="circ_a">
                <circle class="circs" cx="100" cy="100" r="80" fill="#CFC4C7"/>
                <text x="50%" y="50%" class="text_1" text-anchor="middle" style="font-family: 'Raleway', sans-serif;">{{ categoria.nombre }}{% if not forloop.last %}{% endif %}</text>
              </a>
            </svg>
          </div>
          {% endfor %}
        <a class="carousel-control-prev" href="#carouselcat" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true" style="background-color: #1f1f1f;"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselcat" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true" style="background-color: #1f1f1f;">
          </span><span class="sr-only">Next</span>
        </a>
      </div> 
    </div>
  </div>
  <a class="mas_" href="{% url 'shop:categorias' %}" data-toggle="tooltip" title="Ver Mas"><i class="fas fa-chevron-right"></i></a>
</div>
<div class="nuevos">
  <h4 class="sub">Ultimos ingresos</h4>
  <div class="nuevos_items">
    {% if not forloop.last %}
    {% for item in nuevos %}
        <div class="cat_obj">
            <a href="{% url 'shop:item_detalles' id=item.id %}">
              <img class="img_in_cat" src={% if item.imagen %}'{{item.imagen.url}}'{% endif %}>
              <p class="p_item_cat2">{{ item.nombre }}</p>
              <p class="p_item_cat">$ {{ item.precio }}</p>
            </a>
        </div>
    {% endfor %}
    {% endif %}
  </div>
</div>
<h4 class="sub" id="sub_02">Ultimos ingresos</h4>
<div class="nuevos_carousel">
  <div id="my_carousel" class="carousel slide" data-ride="carousel">
    <div class="carousel-inner" role="listbox">
        {% for item in nuevos %}
        {% if forloop.counter == 1 %}
          <div class="carousel-item active">
        {% else %}
          <div class="carousel-item">
        {% endif %}
            <div class="cat_obj2">
              <a href="{% url 'shop:item_detalles' id=item.id %}">
                <img  id="img_cat" class="img_in_cat" src={% if item.imagen %}'{{item.imagen.url}}'{% endif %}>
                <p class="p_item_cat2" id="p1">{{ item.nombre }}</p>
                <p class="p_item_cat" id="p2">$ {{ item.precio }}</p>
              </a>
            </div>
         </div>
         {% endfor %}
      </div>
      <a class="carousel-control-prev" href="#my_carousel" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true" style="background-color: #1f1f1f;"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="carousel-control-next" href="#my_carousel" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true" style="background-color: #1f1f1f;"></span>
        <span class="sr-only">Next</span>
      </a>
    </div>
  </div>
</div>

{% endblock %}

templates/shop/resultados.html
{% extends 'base.html' %}
{% block header %}
{% endblock %}
{% block content %}
<div class="resultado_items">
    <h1 class="sub" id="sub_01">Resultados para tu busqueda</h1>
    <div class="cat_">
        {% if not forloop.last %}
        {% if objetos %}
        {% for item in objetos %}
            <div class="cat_obj">
                <a href="{% url 'shop:item_detalles' id=item.id %}">
                    <img class="img_in_cat" src={% if item.imagen %}'{{item.imagen.url}}'{% endif %}>
                    <p class="p_item_cat2">{{ item.nombre }}</p>
                    <p class="p_item_cat">$ {{ item.precio }}</p>
                </a>
            </div>
        {% endfor %}
        {% else %}
        <h3>Lo sentimos no hay resultados diponibles para tu busqueda</h3>
        {% endif %}
        {% endif %}
    </div>
    <div class="cat_res">
        <h1 class="sub">Resultados para tu busqueda</h1>
        {% for item in objetos %}
        <div class="cat_obj3">
            <a href="{% url 'shop:item_detalles' id=item.id %}">
                <img class="img_in_cat" src={% if item.imagen %}'{{item.imagen.url}}'{% endif %}>
                <p class="p_item_cat2">{{ item.nombre }}</p>
                <p class="p_item_cat">$ {{ item.precio }}</p>
            </a>
        </div>
    {% endfor %} 
    </div>
</div>

{% endblock %}