shop/urls.py
from django.urls import path
from shop import views
from .views import index, cat_obj, item_detalles, guardar_item, add_to_cart, ver_carrito, ver_favoritos, quitar_del_carrito, buscador, buscador_ajax, comentarios, categorias, vaciar_carro
from django.contrib.auth.decorators import login_required
app_name = 'shop'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:id>/items/', views.cat_obj, name='cat_obj'),
    path('categorias/', views.categorias, name='categorias'),
    path('<int:id>/items/detalles/', views.item_detalles, name='item_detalles'),
    path('<int:id>/guardar/', views.guardar_item, name='guardar'),
    path('<int:id>/agregar/', views.add_to_cart, name='add'),
    path('carrito/', login_required(views.ver_carrito), name='carrito'),
    path('favoritos/', login_required(views.ver_favoritos), name='favs'),
    path('<int:id>/quitar/', login_required(views.quitar_del_carrito), name='quitar'),
    path('buscar/', views.buscador, name='buscar'),
    path('resultadosajax/', views.buscador_ajax, name='buscar_ajax'),
    path('<int:id>/comentar/', login_required(views.comentarios), name='comentarios'),
    path('vaciar/', views.vaciar_carro, name='vaciar'),
]

shopIT/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import logout_then_login

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls')),
    path('usuario/', include('usuario.urls')),
    path('logout/', logout_then_login, name='logout')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

usuario/urls.py
from django.urls import path
from usuario import views
from .views import usuario_nuevo, index, login
from django.contrib.auth.decorators import login_required

app_name = 'usuario'

urlpatterns = [
    path('index/', login_required(views.index), name='index'),
    path('registrar/', views.usuario_nuevo, name='nuevo'),
    path('login/', views.login_user, name='log'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Raleway&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Barlow+Condensed&display=swap" rel="stylesheet">
    <title>ShopIT</title>
</head>
<body>
    {% block header %}
    <div class="header">
        <div class="titulo_principal">
            <a href="{% url 'shop:index' %}">ShopIT</a>
        </div>
        <div class="buscador">
            <form id="search" action="/buscar/">
                <input type="search" id="input_search" name="q" placeholder="Buscar productos">
                <button type="submit" id="submit_search"><i class="fas fa-search"></i></button>
            </form>
        </div>
        <div class="re_busquedas" style="display:none;width: 420px;background-color: #fde9cc;padding: 8px;grid-column:3/5;grid-row:2;position: absolute;z-index:99;">
        </div>
        <div class="nav">
            {% if request.user.is_authenticated %}
                <a href="{% url 'shop:carrito' %}" data-toggle="tooltip" title="Ver Carrito"><i class="fas fa-cart-plus"></i></a>
                <a href="{% url 'shop:favs' %}" data-toggle="tooltip" title="Items Guardados"><i class="far fa-heart"></i></a>
                <button id="cuenta_aut" data-toggle="modal" data-target="#modalcuenta_aut"><i class="far fa-user"></i></button>
            {% else %}
                <a href="" data-toggle="tooltip" title="Logueate o registrate"><i class="fas fa-cart-plus"></i></a>
                <a href="" data-toggle="tooltip" title="Logueate o registrate"><i class="far fa-heart"></i></a>
                <button id="cuenta" data-toggle="modal" data-target="#modalcuenta"><i class="far fa-user"></i></button>
            {% endif %} 
        </div>
        <button id="bars"><i class="fas fa-bars"></i></button>
    </div>
    <div class="nav_responsive">
        <div class="buscador">
            <form id="search" action="/buscar/">
                <input type="search" id="input_search" name="q" placeholder="Buscar productos">
                <button type="submit" id="submit_search"><i class="fas fa-search"></i></button>
            </form>
        </div>
        <div class="menu">
            {% if request.user.is_authenticated %}
            <a href="{% url 'shop:carrito' %}"><i class="fas fa-cart-plus"></i> Ver Carrito</a>
            <a href="{% url 'shop:favs' %}"><i class="far fa-heart"></i> Ver Guardados</a>
            <button id="cuenta_aut" data-toggle="modal" data-target="#modalcuenta_aut"><i class="far fa-user"></i> Cuenta</button>
        {% else %}
            <a href="" data-toggle="tooltip" title="Logueate o registrate"><i class="fas fa-cart-plus"></i> Ver Carrito</a>
            <a href="" data-toggle="tooltip" title="Logueate o registrate"><i class="far fa-heart"></i> Ver Guardados</a>
            <button id="cuenta" data-toggle="modal" data-target="#modalcuenta"><i class="far fa-user"></i> Cuenta</button>
        {% endif %} 
        </div>
    </div>
    <div class="modal fade" id="modalcuenta" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content" id="modal3">
                <div class="modal-header text-center">
                    <h4 class="modal-title w-100" id="modaltit">Cuenta</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body mx-3" id="control">
                    <div class="md-form mb-5 mt-4 d-flex justify-content-center">
                        <button class="btn_1" id="login" data-toggle="modal" data-target="#modalLoginForm">Iniciar Sesion</button>
                    </div>
                    <div class="md-form mb-5 d-flex justify-content-center">
                        <button class="btn_1" id="register" data-toggle="modal" data-target="#modalRegisterForm">Registrarse</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="modal fade" id="modalcuenta_aut" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content" id="modal3">
                <div class="modal-header text-center">
                    <h4 class="modal-title w-100" id="modaltit">Cuenta</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body mx-3" id="control">
                    <div class="md-form mb-5 mt-4 d-flex justify-content-center">
                        <a class="user_page" href="{% url 'usuario:index' %}">{{ request.user.username }}</a>
                    </div>
                    <div class="md-form mb-5 d-flex justify-content-center">
                        <a class="logout" href="{% url 'logout' %}">Salir <i id="salir" class="fas fa-sign-out-alt"></i></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="modal fade" id="modalRegisterForm" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content" id="modal">
                <div class="modal-header text-center">
                    <h4 class="modal-title w-100" id="modaltit">Registrarse</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <form id="registerform">
                    {% csrf_token %}
                    <div class="modal-body mx-3" id="control">
                        <div class="md-form mb-5 mt-4">
                            <input type="text" class="form-control validate" name="username" placeholder="Nombre de Usuario">
                        </div>
                        <div class="md-form mb-5">
                            <input type="text" class="form-control validate" name="first_name" placeholder="Nombre">
                        </div>
                        <div class="md-form mb-5">
                            <input type="text" class="form-control validate" name="last_name" placeholder="Apellido">
                        </div>
                        <div class="md-form mb-5">
                            <input type="email" class="form-control validate" name="email" placeholder="Email">
                        </div>
                        <div class="md-form mb-5">
                            <input type="password" class="form-control validate" name="password" placeholder="Contraseña">
                        </div>
                        <div class="md-form mb-5">
                            <input type="password" class="form-control validate" name="password2" placeholder="Confirmar">
                        </div>
                    </div>
                    <div class="modal-footer d-flex justify-content-center">
                        <a href="{% url 'usuario:nuevo' %}" id="submit_reg" class="btnreg">Registrarse</a>
                        <div class="errores"></div>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <div class="modal fade" id="modalLoginForm" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content" id="modal">
                <div class="modal-header text-center">
                    <h4 class="modal-title w-100" id="modaltit">Loguearse</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <form id="loginform">
                    {% csrf_token %}
                    <div class="modal-body mx-3" id="control">
                        <div class="md-form mb-5 mt-4">
                            <input type="text" class="form-control validate" name="username" placeholder="Nombre de Usuario">
                        </div>
                        <div class="md-form mb-5">
                            <input type="password" class="form-control validate" name="password" placeholder="Contraseña">
                        </div>
                    </div>
                    <div class="modal-footer d-flex justify-content-center">
                        <a href="{% url 'usuario:log' %}" id="submit_login" class="btnreg">Loguearse</a>
                        <div class="errores2"></div>
                    </div>
                </form>
            </div>
        </div>
    </div>
    {% endblock %}
    {% block content %}
    {% endblock %}
    {% block footer %}
    <div class="footer">
        <h4>ShopIT</h4>
        <p>Copyright 2020 | Todos los derechos reservados</p>
    </div>
    {% endblock %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
	<script src="{% static 'js/codigo.js' %}"></script>
</body>
</html>